### ISSUE TITLE
Type error with v6.7.6

### ISSUE THREAD

**Issue by avogt1701** [franzholz/static_info_tables_de#13]
There is a type error due to the missing legacy extbase configuration. I get the error "TypeError: property_exists() expects parameter 2 to be string, null given" after a getNameLocalized() call for a country model. 

The legacy configuration (https://github.com/franzholz/static_info_tables_de/blob/master/ext_localconf.php#L5-L10) is in TYPO3 10 still necessarry. It is used in the static_info_tables ModelUtility: https://github.com/TYPO3-extensions/static_info_tables/blob/master/Classes/Utility/ModelUtility.php#L65-L70 . And this mapping is required for the getNameLocalized method: https://github.com/TYPO3-extensions/static_info_tables/blob/master/Classes/Domain/Model/AbstractEntity.php#L90

**Comment by franzholz** [comment]
Does it work with this bugfix?

**Comment by avenit-avo** [comment]
Yes. Works 👍
