### ISSUE TITLE
Wrong class is loaded in TYPO3 v10.4.17

### ISSUE THREAD

**Issue by nicodh** [franzholz/static_info_tables_de#14]
I get an error TYPO3\CMS\Extbase\Persistence\Generic\Mapper\Exception\NonExistentPropertyException from typo3/sysext/extbase/Classes/Persistence/Generic/Mapper/DataMapper.php line 256
`
"The type of property SJBR\StaticInfoTables\Domain\Model\Country::addressFormat could not be identified, as property addressFormat is unknown to the TYPO3\CMS\Extbase\Reflection\ClassSchema instance of class SJBR\StaticInfoTables\Domain\Model\Country"
`
each time after clearing cache when loading a property of type \SJBR\StaticInfoTables\Domain\Model\Country in an extbase model. It seems that only the class from static_info_tables_de/Classes/Domain/Model/Country.php is loaded thus the other properties are missing. The reflection class schema in DataMapper shows only the properties from the _de class.

The error happens in Datamapper in thawProperties.

Both Classes have the exact same name and namespace... ??

**Comment by franzholz** [comment]
Problems of this kind should be reported directly to static_info_tables.

**Comment by nicodh** [comment]
But if I uninstall static_info_tables_de it works as expected?

**Comment by nicodh** [comment]
Ah ok - I see. The extending magic happens in static_info_tables. So you can close this issue...

**Comment by franzholz** [comment]
All these additional extensions are only written following the documentations coming from static_info_tables.
