### ISSUE TITLE
typo3cms extension:setupactive fails on 6.7.11

### ISSUE THREAD

**Issue by secured** [franzholz/static_info_tables_de#19]
composer.json:
```
"typo3/cms-ore": "^10.4",
 "helhum/typo3-console": "^6.3",
"sjbr/static-info-tables": "^6.9",
"jambagecom/static-info-tables-de": "6.7.11",
```

command "vendor/bin/typo3cms extension:setupactive" is giving this error:

```
 [ TYPO3\CMS\Extensionmanager\Exception\ExtensionManagerException ]
  Requested update script of extension does not exist
```

everything is fine with 6.7.10

**Comment by dahaupt** [comment]
I think this is based on an issue in v6 of `sjbr/static-info-tables`. In the current state, the `class.ext_update.php` file must be present as [the slot misses](https://codeberg.org/sjbr/static-info-tables/src/tag/v6.9.5/Classes/Slot/Extensionmanager/AfterExtensionInstall.php#L90) the `checkUpdateScriptExists()` call.

I can open a PR, but I am not sure if v6 is still maintained.

Edit: @franzholz As there is no dev-branch available, the only solution to me seems to keep the file when supporting v6 of `sjbr/static-info-tables`.

**Comment by simonschaufi** [comment]
same is true for `static_info_tables_es`
